# Generated by Django 2.1.7 on 2019-03-30 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190331_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 30, 18, 23, 43, 645000, tzinfo=utc)),
        ),
    ]
