# Generated by Django 2.1.7 on 2019-03-31 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190331_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 31, 7, 0, 47, 165000, tzinfo=utc)),
        ),
    ]
